#!/usr/bin/env python3
"""Aggregate Bill of Materials CSV files into a master report.

This script is deliberately verbose and beginner-friendly. It validates column
headers, parses numeric fields, calculates totals, and writes both CSV and
Markdown summaries. Any errors are reported with actionable tips so newcomers
can fix issues quickly.
"""

from __future__ import annotations

import csv
import glob
import pathlib
import sys
from collections import defaultdict
from dataclasses import dataclass
from typing import Dict, List

# Constants -------------------------------------------------------------------
REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
HARDWARE_DIR = REPO_ROOT / "hardware"
MASTER_CSV = HARDWARE_DIR / "bom_master.csv"
MASTER_MD = HARDWARE_DIR / "bom_master.md"
REQUIRED_HEADER = [
    "Category",
    "Subcategory",
    "Item",
    "Manufacturer",
    "Model/Part#",
    "Supplier",
    "Supplier SKU",
    "URL",
    "Qty",
    "Unit",
    "Unit Price (USD)",
    "Total Price (USD)",
    "Unit Weight (g)",
    "Total Weight (g)",
    "Voltage",
    "Current",
    "Notes",
    "Version/Rev",
    "Footprint/Size",
    "Where Installed",
]

NUMERIC_FIELDS = {
    "Qty",
    "Unit Price (USD)",
    "Total Price (USD)",
    "Unit Weight (g)",
    "Total Weight (g)",
    "Voltage",
    "Current",
}

# Data classes ----------------------------------------------------------------
@dataclass
class Row:
    """Holds a single row of the BoM with parsed numeric fields."""

    data: Dict[str, str]
    source_file: pathlib.Path
    build_section: str

    def numeric(self, key: str) -> float:
        """Return the numeric value for `key`, treating blanks as zero.

        Args:
            key: Column name to fetch.

        Returns:
            Float representation of the cell. Empty strings become 0.0.
        """

        raw = self.data.get(key, "").strip()
        if not raw:
            return 0.0
        try:
            return float(raw)
        except ValueError as exc:  # pragma: no cover - defensive
            raise ValueError(
                f"Invalid number '{raw}' in column '{key}' of {self.source_file}"
            ) from exc


# Helper functions -------------------------------------------------------------
def read_csv(path: pathlib.Path) -> List[Row]:
    """Read a BoM CSV and return rows with validation.

    Args:
        path: Path to the CSV file.

    Returns:
        List of `Row` instances ready for aggregation.
    """

    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        header = reader.fieldnames or []
        missing = [col for col in REQUIRED_HEADER if col not in header]
        if missing:
            raise SystemExit(
                f"Error: Missing columns in {path.name}: {', '.join(missing)}"
            )

        rows: List[Row] = []
        build_section = path.stem.replace("bom_", "").title()
        for raw_row in reader:
            if not any(value.strip() for value in raw_row.values()):
                continue  # Skip completely blank rows
            for field in NUMERIC_FIELDS:
                _ = Row({**raw_row}, path, build_section).numeric(field)
            rows.append(Row(raw_row, path, build_section))
        return rows


def write_master_csv(rows: List[Row]) -> None:
    """Write the combined CSV including the build section column."""

    header = REQUIRED_HEADER + ["Build Section"]
    with MASTER_CSV.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=header)
        writer.writeheader()
        for row in rows:
            output = dict(row.data)
            output["Build Section"] = row.build_section
            writer.writerow(output)


def write_master_md(rows: List[Row], totals: Dict[str, float]) -> None:
    """Write a Markdown summary with totals and subtotals."""

    with MASTER_MD.open("w", encoding="utf-8") as handle:
        handle.write("# Combined Bill of Materials\n\n")
        handle.write("Generated by `tools/bom_aggregate.py`. Do not edit manually.\n\n")

        handle.write("## Grand Totals\n\n")
        handle.write(
            f"* **Total Cost:** ${totals['cost']:.2f}\n"
            f"* **Total Weight:** {totals['weight']:.1f} g\n\n"
        )

        handle.write("## Subtotals by Build Section\n\n")
        for section, values in sorted(totals["section"].items()):
            handle.write(
                f"* **{section}:** ${values['cost']:.2f}, {values['weight']:.1f} g\n"
            )
        handle.write("\n")

        handle.write("## Subtotals by Category\n\n")
        for category, values in sorted(totals["category"].items()):
            handle.write(
                f"* **{category}:** ${values['cost']:.2f}, {values['weight']:.1f} g\n"
            )
        handle.write("\n")

        handle.write("## Detailed Items\n\n")
        handle.write(
            "| Build Section | Category | Item | Qty | Unit | Total Price (USD) | Total Weight (g) | Where Installed |\n"
        )
        handle.write(
            "|---------------|----------|------|-----|------|--------------------|------------------|-----------------|\n"
        )
        for row in rows:
            handle.write(
                "| {section} | {category} | {item} | {qty} | {unit} | ${price:.2f} | {weight:.1f} | {where} |\n".format(
                    section=row.build_section,
                    category=row.data.get("Category", ""),
                    item=row.data.get("Item", ""),
                    qty=row.data.get("Qty", ""),
                    unit=row.data.get("Unit", ""),
                    price=row.numeric("Total Price (USD)"),
                    weight=row.numeric("Total Weight (g)"),
                    where=row.data.get("Where Installed", ""),
                )
            )


def compute_totals(rows: List[Row]) -> Dict[str, float]:
    """Compute grand totals and subtotals."""

    totals = {
        "cost": 0.0,
        "weight": 0.0,
        "section": defaultdict(lambda: {"cost": 0.0, "weight": 0.0}),
        "category": defaultdict(lambda: {"cost": 0.0, "weight": 0.0}),
    }

    for row in rows:
        cost = row.numeric("Total Price (USD)")
        weight = row.numeric("Total Weight (g)")
        totals["cost"] += cost
        totals["weight"] += weight
        section_entry = totals["section"][row.build_section]
        section_entry["cost"] += cost
        section_entry["weight"] += weight
        category_entry = totals["category"][row.data.get("Category", "Unknown")]
        category_entry["cost"] += cost
        category_entry["weight"] += weight

    return totals


def main() -> None:
    """Entry point for the CLI."""

    csv_paths = sorted(glob.glob(str(HARDWARE_DIR / "bom_*.csv")))
    csv_paths = [path for path in csv_paths if not path.endswith("bom_master.csv")]
    if not csv_paths:
        raise SystemExit("Error: No bom_*.csv files found in hardware/ directory.")

    rows: List[Row] = []
    for path_str in csv_paths:
        path = pathlib.Path(path_str)
        rows.extend(read_csv(path))

    if not rows:
        raise SystemExit("Error: No rows found in any BoM CSV files.")

    write_master_csv(rows)
    totals = compute_totals(rows)
    write_master_md(rows, totals)

    print("BoM aggregation complete. Summary:")
    print(f"  Total cost: ${totals['cost']:.2f}")
    print(f"  Total weight: {totals['weight']:.1f} g")
    print("  Sections:")
    for section, values in sorted(totals["section"].items()):
        print(
            f"    - {section}: ${values['cost']:.2f}, {values['weight']:.1f} g"
        )


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # pragma: no cover - user-friendly exit
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)
