[platformio]
default_envs = headset_esp32, drone_esp32
src_dir = .

[env]
platform = espressif32@6.5.0
framework = arduino
board = esp32dev
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
lib_deps =
    Wire
    ESP32Servo
    https://github.com/espressif/arduino-esp32.git

[env:headset_esp32]
src_filter = +<common> +<headset>
build_flags =
    ${env.build_flags}

[env:drone_esp32]
src_filter = +<common> +<drone>
build_flags =
    ${env.build_flags}


