[platformio]
default_envs = headset_esp32_espnow, drone_esp32_espnow
src_dir = .

[env]
platform = espressif32@6.5.0
framework = arduino
board = esp32dev
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
lib_deps =
    Wire
    ESP32Servo
    https://github.com/espressif/arduino-esp32.git

[env:headset_esp32_espnow]
src_filter = +<common> +<headset> -<common/transport_espnow.cpp> -<common/transport_hc12.cpp>
build_flags =
    ${env.build_flags}
    -DHEADSET_SIDE
    -DTRANSPORT_ESP_NOW

[env:drone_esp32_espnow]
src_filter = +<common> +<drone> -<common/transport_espnow.cpp> -<common/transport_hc12.cpp>
build_flags =
    ${env.build_flags}
    -DDRONE_SIDE
    -DTRANSPORT_ESP_NOW

[env:headset_esp32_hc12]
src_filter = +<common> +<headset> -<common/transport_espnow.cpp> -<common/transport_hc12.cpp>
build_flags =
    ${env.build_flags}
    -DHEADSET_SIDE
    -DTRANSPORT_HC12

[env:drone_esp32_hc12]
src_filter = +<common> +<drone> -<common/transport_espnow.cpp> -<common/transport_hc12.cpp>
build_flags =
    ${env.build_flags}
    -DDRONE_SIDE
    -DTRANSPORT_HC12

[env:headset_esp32]
extends = headset_esp32_hc12

[env:drone_esp32]
extends = drone_esp32_hc12

